#!/usr/bin/env bash
#script to install and configure HAProxy on lb-01 server
#!/usr/bin/env bash
# configures a new HAproxy as a load balancer
# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.8.\*
# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend gang-gang.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
           server 332201-web-01 35.153.255.129:80 check
           server 332201-web-02 100.26.226.51:80 check
' >> /etc/haproxy/haproxy.cfg
# Restart HAproxy service
service haproxy restart
