#!/usr/bin/env bash
#Script that connects to server without typing a password

Host *
	PasswordAuthentication yes
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication es
	GSSAPIdelegateCredentials no
